### ISSUE TITLE
loadingDelay配合element-plus中的v-loading指令一起使用时异常

### ISSUE THREAD

**Issue by jamessawyer** [InhiblabCore/vue-hooks-plus#10]
这个问题很奇怪，打印 `loading` 值显示的是 `false`, 但是将值传入到 `v-loading` 时，`delayLoading` 好像就失效了，部分代码如下：
```vue
<script  lang="ts" setup>
function getUsername(): Promise<string> {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('vue-hooks-plus useRequest');
    }, 4000);
  });
}

const { data, loading } = useRequest(() => getUsername(), {
  loadingDelay: 2000,
});
<script>

<template>
  <div v-loading="loading">
    <h1>🚀 loading {{ loading ? '加载中' : data }}</h1>
    <h1>😶‍🌫️ loading {{ loading }}</h1>

    <h2>🔥 myLoading: {{ myLoading }}</h2>
    <el-button @click="toggleMyLoading" type="primary">Element</el-button>
  </div>
</template>
```
在线链接：[vue-hooks-plus-delayLoading - stackblitz](https://stackblitz.com/edit/vitejs-vite-mpxwse?file=src/App.vue)
很明显可以看到，显示了2次loading。

我看源码，`loadingDelay` 好像用的是 [useLoadingDelayPlugin](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/packages/hooks/src/useRequest/plugins/useLoadingDelayPlugin.ts#L22)
```typescript
 onBefore: () => {
      cancelTimeout();
      timerRef.value = setTimeout(() => {
        fetchInstance.setState({
          loading: true,
        });
      }, (isRef(loadingDelay) ? loadingDelay.value : loadingDelay) as number);

      return {
        loading: false,
      };
    },
```
看这段代码好像没什么问题，还请大佬指点。
ps: [element-plus loading](https://element-plus.org/zh-CN/component/loading.html#%E9%85%8D%E7%BD%AE%E9%A1%B9)

**Comment by NelsonYong** [comment]
@jamessawyer 是我在初始化状态的时候给了loading为true，但是实际情况是需要为false的，所以就导致刚开始时v-loading 取得是true，但在before的时候我又给了false，timeout又设置为true，所以就会导致loading在一开始会跑然后停止然后再loading [在线地址](https://stackblitz.com/edit/vitejs-vite-xesh7t?file=package.json) 现在已经更新到1.1.3版本

**Comment by jamessawyer** [comment]
明白了，我没仔细看源代码，以为没有给 `loading` 设置默认值，以为初始是 `undefined`。感谢及时更新，这个库对于用过 `ahooks` 的人还挺不错的👍

**Comment by NelsonYong** [comment]
感谢大兄弟支持，也希望得到更多人的支持，完善这个库，因为我就是觉得vueuse用不习惯才写的 @jamessawyer
