### ISSUE TITLE
日志代码没有清除

### ISSUE THREAD

**Issue by itmanyong** [InhiblabCore/vue-hooks-plus#102]
### Describe the bug

在代码热更新时触发输出以下内容
![image](https://user-images.githubusercontent.com/53500371/218417672-913596e8-ae08-49d9-81e0-29eb3916fd8d.png)
输出位置位于
![image](https://user-images.githubusercontent.com/53500371/218417777-b6a43826-b71b-41b4-8a06-b1fd2ad109e3.png)

### System Info

```shell
其他无关
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NelsonYong** [comment]
> ### Describe the bug
> 在代码热更新时触发输出以下内容 ![image](https://user-images.githubusercontent.com/53500371/218417672-913596e8-ae08-49d9-81e0-29eb3916fd8d.png) 输出位置位于 ![image](https://user-images.githubusercontent.com/53500371/218417777-b6a43826-b71b-41b4-8a06-b1fd2ad109e3.png)
> 
> ### Steps to reproduce
> _No response_
> 
> ### System Info
> ```shell
> 其他无关
> ```
> 
> ### Used Package Manager
> pnpm
> 
> ### Validations
> * [x]  Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
> * [x]  Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
> * [x]  Read the [docs](https://inhiblabcore.github.io/docs/hooks).
> * [x]  Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
> * [x]  Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
> * [x]  Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
> * [x]  The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

PR: #103 
version: v1.6.0-alpha.3
