### ISSUE TITLE
请教关于useRequest的一个问题

### ISSUE THREAD

**Issue by joanoor** [InhiblabCore/vue-hooks-plus#106]
你好，我在写vue3+typescript+element-plus的时候，有个问题。考虑一个场景：当使用el-tab切换的时候，需要调用不同的接口，然后放到下面的el-table中。
想请问下，以前在vue2中，都是定义一个tableData，调用不同的接口可以将数据赋值给tableData，然后给el-table的data，现在vue3中请问是不是每切换一次el-tab，都要执行一下useRequest？
![Snipaste_2023-02-15_20-44-18](https://user-images.githubusercontent.com/2725041/219031511-82222ea9-8264-4c86-ba13-50b2a2d73616.png)

**Comment by joanoor** [comment]
如果不需要每切换一次el-tab就调用一下useRequest，那如何动态改变data的ts类型？

**Comment by NelsonYong** [comment]
> 如果不需要每切换一次el-tab就调用一下useRequest，那如何动态改变data的ts类型？

我认为这个在接口设计上存在一定问题，有效无效和全部正常情况下应该是同一个接口不同的参数，每次切换tab传入不同的参数即可。
如果是不同接口，我的做法，会新建一个hook，里面写一个tabledata的ref，然后里面写三份useRequest，通过ready来控制，ready为true即会发送请求，在onsuccess处进行tabledata的赋值

**Comment by NelsonYong** [comment]
> 如果不需要每切换一次el-tab就调用一下useRequest，那如何动态改变data的ts类型？

ts是静态类型，不能动态改变哦 @joanoor
