### ISSUE TITLE
打包报错问题

### ISSUE THREAD

**Issue by w611363303798** [InhiblabCore/vue-hooks-plus#112]
### Describe the bug

1.6.0-alpha.7 按需引入vite打包报错，全量引入正常
1.6.0-alpha.2正常
![image](https://user-images.githubusercontent.com/24557962/219933842-bfb96036-0eab-4796-8eff-15cc87f5461f.png)

### System Info

```shell
Windows 10，node版本16.18.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NelsonYong** [comment]
@w611363303798 可能是类型导出缺少type，周一修复

**Comment by NelsonYong** [comment]
可以先用着2版本，后面的版本变动不大

**Comment by NelsonYong** [comment]
可以提供一个最小复现吗，方便我排查问题

**Comment by NelsonYong** [comment]
packagejson里面的导出路径有误，请关注后续版本更新 @w611363303798

**Comment by NelsonYong** [comment]
@w611363303798  已经更新 1.6.0-alpha.8 版本修复
