### ISSUE TITLE
Maybe typo in docs useRequest/refreshDeps

### ISSUE THREAD

**Issue by wheeljs** [InhiblabCore/vue-hooks-plus#118]
### Describe the bug

When I see useRequest's documentation, in "RefreshDeps" page, I see a remark below.

> Only the automatic mode mode, that is, manual is true, depends on the new configuration of swiping the card to have an effect. Manual mode requires users to manage requests themselves.

I think that `manual=true` may not means automatic mode, it means manual mode. There is are 'mode' in the first sentence.

Maybe it's me misunderstanding.

### System Info

```shell
macOS Monterey 12.5.1
Chrome 110.0.5481.100 (Official Build) (x86_64)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NelsonYong** [comment]
@wheeljs Thanks for your feedback, I think there are some issues with this sentence and I have made a change. 👇
When the automatic mode (`manual! = true`) and `refreshDeps ` will take effect.

**Comment by NelsonYong** [comment]
PR: #119 
https://inhiblabcore.github.io/docs/hooks/en/useRequest/refreshDeps
