### ISSUE TITLE
useRequest能够支持多请求吗

### ISSUE THREAD

**Issue by cnelf** [InhiblabCore/vue-hooks-plus#121]
### Describe the bug

这边的理想使用场景是可以处理多请求的情况，像是这样：
const { data: [res1, res2], loading, error } = useRquest([requestFn1, requestF2], options)
主要好处是可以只维护一个loading状态

### System Info

```shell
no content
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NelsonYong** [comment]
这个多个请求不考虑，因为有现成的方案，有两种方法，一种是vue允许自己循环维护多个userequest，第二种是比较推荐的使用runasync循环，使用promise all自己管理。
