### ISSUE TITLE
想理解下 useRequest 中 cancel 是如何使用的

### ISSUE THREAD

**Issue by 6313504** [InhiblabCore/vue-hooks-plus#123]
### Describe the bug

源码中 onCancel 是什么 需要做什么，
axios 中的 cancelToken 如何能集成在 useRequest中

### System Info

```shell
无
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NelsonYong** [comment]
@6313504  cancel用于取消请求，但不是通过abort去中断取消请求，而是通过改变count，直到异步函数开始响应的时候，然后比较count，不一致就直接返回 `new Promise(() => {})`达到取消请求的，但实际上promise还是会执行。
所以，我们要达到使用axios中的cancelToken取消请求，需要自己写插件，当用户执行cancel的时候会运行插件中的`onCancel `的钩子，钩子里面使用cancelToken即可。具体插件设计可以参考文档
