### ISSUE TITLE
从1.5升级到1.6后出现警告

### ISSUE THREAD

**Issue by MangMax** [InhiblabCore/vue-hooks-plus#125]
### Describe the bug

升级版本以后使用fetch出现这样的警告
![image](https://user-images.githubusercontent.com/68525017/226817310-790841f9-be59-453e-99b7-f8eb4912f36d.png)
查看源码是在这里读取的这个值
![image](https://user-images.githubusercontent.com/68525017/226817435-c63bc9bb-ec7d-4404-815a-b50146a1fe20.png)
请问我该怎么避免这个警告

### System Info

```shell
Windows 
chrome
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NelsonYong** [comment]
因为在获取global option的时候，父没有provider，inject匹配不到key，请关注一下明天的更新修复版本 @MangMax

**Comment by MangMax** [comment]
好的，谢谢

**Comment by MangMax** [comment]
> 
好的，谢谢

**Comment by MangMax** [comment]
> 因为在获取global option的时候，父没有provider，inject匹配不到key，请关注一下明天的更新修复版本 @MangMax

好的，谢谢

**Comment by NelsonYong** [comment]
@MangMax 
- version: `v1.6.2`
- PR: #126
