### ISSUE TITLE
对 useRequest 的 demo 有疑惑，最终返回的 data 是 undefined

### ISSUE THREAD

**Issue by Jake-00** [InhiblabCore/vue-hooks-plus#134]
### Describe the bug

我根据官方文档中的 [useRequest 规范](https://inhiblab-core.gitee.io/docs/hooks/useRequest/guide/)，一步一步走，修改的代码如下，运行 npm run dev 后没有显示 data 的值。
services.ts
```ts
import { request } from '../../network/axios'
import { NameType } from './data.d'

export async function getUserInfo() {
  return request<NameType>('https://www.fastmock.site/mock/ca8533cc667844de72db39a6b8ab925a/quiz/id')
}
```

data.d.ts
```ts
export type NameType = {
    desc: string
}
```
紧接着我 debug 了一下，发现 res 已经得到了数据，但return type显示为 undefined，期待大佬们答疑解惑
![image](https://user-images.githubusercontent.com/60967034/236410239-a7ecb442-bc98-4c97-bff8-1bf98569c906.png)

### System Info

```shell
Windows 11
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Jake-00** [comment]
后面把 `.then( res => resolve(res.data))` 修改成 `.then( res => resolve(res))` 就能正常显示

**Comment by NelsonYong** [comment]
是的，因为request实体是用户去自定义的，拦截器那边返回的格式因人而异，只需要返回data即可，我的那个例子只是使用了
```
code,
data,
msg
```
的格式，所以需要返回 `res.data`

**Comment by NelsonYong** [comment]
感谢你的提醒，我后续会修改一下规范

**Comment by Jake-00** [comment]
项目很棒，🌟奉上
