### ISSUE TITLE
返回值类型为 readonly

### ISSUE THREAD

**Issue by cnelf** [InhiblabCore/vue-hooks-plus#136]
### Describe the bug

注意到在此次 commit 中把返回值类型改成了 readonly
 https://github.com/InhiblabCore/vue-hooks-plus/pull/132/commits/eda490043748b5e00487599fc728d4e7f59096f6 

之前的代码涉及到修改 loading 和重置 data 相关的操作，因此导致升级依赖后报类型异常

想问是出于什么原因进行的修改？如果我需要清除 data 或者调整 loading 状态应该如何实现呢？

### System Info

```shell
none
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NelsonYong** [comment]
@cnelf ，对于loading的话我是不希望用户去控制它的行为，因为它属于useRequet的一个行为，不应该由开发者去控制，如果需要做自定义，建议新建变量使用计算属性。对于data来说，它有一个突变的方法可以去修改它。其实这也一定程度上使得开发者有负担，但也起到了规范开发者的行为。我的意图就是像我这种工具库里面的响应式对象需要和业务中的变量有区别，如果大家都能随意改动，那会一定程度上的影响我们代码维护的质量。

**Comment by NelsonYong** [comment]
如果还有疑问，我会第一时间回复你 @cnelf

**Comment by cnelf** [comment]
了解，我这边会先锁定 1.6 版本来处理类型问题，后面再规范写法
