### ISSUE TITLE
1.6.5升级到1.7.4useUrlState报错

### ISSUE THREAD

**Issue by MangMax** [InhiblabCore/vue-hooks-plus#143]
### Describe the bug

![image](https://github.com/InhiblabCore/vue-hooks-plus/assets/68525017/afb10ba7-4105-4450-8304-82c1209ebe68)
如图，参照官网例子获取url参数报错
官网例子也无法正常使用
![image](https://github.com/InhiblabCore/vue-hooks-plus/assets/68525017/1ab26cff-d8fd-4ee8-963b-8d7a897b81da)

### Steps to reproduce

在axios中使用
`const default_state = { token: "" };`
`let url_token = useUrlState(default_state, {
  localStorageKey: "localStorageKey",
});`
![image](https://github.com/InhiblabCore/vue-hooks-plus/assets/68525017/c3eac7f3-cbfa-4522-bcbc-945510fcd6ca)

### System Info

```shell
windows 11
edge
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NelsonYong** [comment]
@MangMax 我看看

**Comment by NelsonYong** [comment]
@MangMax 请升级 `1.7.5`
- PR: #144 
- 后续这个钩子的计划 #145
