### ISSUE TITLE
useRequest 乐观更新 错误回滚

### ISSUE THREAD

**Issue by yuanjinkunlou** [InhiblabCore/vue-hooks-plus#147]
### Description

很多情况下，应用本地的数据更改是一个让人感觉快速的好方法——不需要等待远程数据源。

### Suggested solution

具体功能可以参考一下 React 的 SWR请求hooks库中的乐观更新和错误回滚

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by NelsonYong** [comment]
目前有乐观更新机制:
https://inhiblabcore.github.io/docs/hooks/useRequest/basic/#%E7%AB%8B%E5%8D%B3%E5%8F%98%E6%9B%B4%E6%95%B0%E6%8D%AE

错误回滚的目前还没有，如果你着急的话可以单独写一个插件在onError的时候共享prev的data，详情可以看插件设计。关于request 竞态问题内核已经支持，你只用关心对data进行保存和设置即可 @yuanjinkunlou

**Comment by NelsonYong** [comment]
PR: #156
Version: `1.7.7-alpha.4`
