### ISSUE TITLE
feat: use longPress function

### ISSUE THREAD

**Issue by erikkkwu** [InhiblabCore/vue-hooks-plus#149]
### Description

i want proposal a feature that contains pressing state, which allows developers to know if a press is ongoing and the duration of the press. This will provide developers with more flexibility, for instance, they can implement features like canceling with a long press, or decide on different actions based on the duration of the press.

I can submit PR for this feature propose

### Suggested solution

listener mouse event to controller pressing state  

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by NelsonYong** [comment]
Thank you very much for your support 🌸. This library lacks this function, and I look forward to your implementation.

**Comment by NelsonYong** [comment]
#150

**Comment by NelsonYong** [comment]
https://inhiblabcore.github.io/docs/hooks/useLongPress/
