### ISSUE TITLE
useInfiniteScroll 滚动无法触发 

### ISSUE THREAD

**Issue by jc840031139** [InhiblabCore/vue-hooks-plus#153]
### Describe the bug

useInfiniteScroll 滚动无法触发 

`useInfiniteScroll(
  async () => {
    const res = await getMerchantList()
    console.log(res)
    return { list: res.records, ...res }
  },
  {
    target: document.documentElement
  }
)`

document.documentElement.scrollTop可以取到值

我滚动的区域是整个页面 

### System Info

```shell
mac m1
google 113.0.5672.63
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NelsonYong** [comment]
html 标签本身是没有滚动事件的，所以无法监听滚动事件，望悉知。建议采用其他高度固定的元素替代。@jc840031139
