### ISSUE TITLE
useRequest方法中配置项onSuccess与解构返回值callback对比（期望新增返回值的回调函数）

### ISSUE THREAD

**Issue by XiaoDaiGua-Ray** [InhiblabCore/vue-hooks-plus#164]
### Description

在使用 useRequest 的时候，如果出现多个并且需要顺序依赖请求的业务场景，使用 onSuccess 配置方法，可能会不太方便。因为大多数情况下，可能需要重复去使用该方法。
<img width="992" alt="image" src="https://github.com/InhiblabCore/vue-hooks-plus/assets/51957438/fa13cc79-e304-468d-9f40-c8d2dc41fab7">

### Suggested solution

像上述问题那样，这样的书写方式并不符合直觉，因为我需要把顺序倒叙的进行声明。如果能够解构的方式，有一个类似于 onSuccess 的回调函数支持，这样就可以不用关注变量声明的顺序，并且更加直观的阅读代码。而且，以返回值形式的回调方法，可以更加灵活的在业务中使用。
<img width="720" alt="image" src="https://github.com/InhiblabCore/vue-hooks-plus/assets/51957438/14fca41d-6f22-48fc-8ede-6aa615d2e0a9">

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by XiaoDaiGua-Ray** [comment]
我也尝试过自定义插件去解决，但是不能很好的解决ts类型问题。并且在返回值这块，也希望能够有更多的拓展性😄😄

**Comment by NelsonYong** [comment]
感谢你的提议，这一块功能会纳入到 2.0 的计划中。欢迎留意后续更新 🥳

**Comment by NelsonYong** [comment]
期望出一个和目前插件式一样nice 的产物

**Comment by NelsonYong** [comment]
目前暂时不考虑哈 🤣
