### ISSUE TITLE
vue2.7 support

### ISSUE THREAD

**Issue by EwanBerg** [InhiblabCore/vue-hooks-plus#165]
### Description

react刚转的vue，特别喜欢用ahooks的useRequest做请求工具。然后现在公司的项目由于需要支持老的浏览器，最多到2.7。试着在vue2.7里面安装了下， 试用了下useRequest，暂时未发现什么问题。请问 不支持vue2 是因为未做详尽的测试吗？

### Suggested solution

期待支持2.7版本。

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by NelsonYong** [comment]
@EwanBerg 之前这个库的时候是始于一年半前，vue 2.x需要 vue-demi 做兼容，但我并没有引入这个库。
vue 2.7，可能官方做了比较好的兼容，如果你运行没什么问题欢迎使用哈，目前我是没做相关测试的

**Comment by NelsonYong** [comment]
近期打算做一个 useRequest 的镜像包，里面会使用 vue-demi 兼容 2.x，这个很多实践的应该没什么问题。主包目前还不会采用 vue-demi，欢迎留意后续更新

**Comment by EwanBerg** [comment]
> 

感谢回复。祝顺利。🥰
