### ISSUE TITLE
renderhook 的问题

### ISSUE THREAD

**Issue by liuxsen** [InhiblabCore/vue-hooks-plus#168]
### Describe the bug

比如在useTitle中，为了检测watch功能，实际上是是多次调用了renderHook；

只是再一次进行了app的创建；并不是watch的效果；有其他方式吗？

### System Info

```shell
node: v16
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by liuxsen** [comment]
![image](https://github.com/InhiblabCore/vue-hooks-plus/assets/12598696/3c9fc362-bc42-4a88-b7e3-a5a6f32e198f)

**Comment by NelsonYong** [comment]
暂时没办法取到替代方案 @liuxsen
