### ISSUE TITLE
复制乱码

### ISSUE THREAD

**Issue by k983551019** [InhiblabCore/vue-hooks-plus#170]
### Describe the bug

复制乱码

### System Info

```shell
win11
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by k983551019** [comment]
![image](https://github.com/InhiblabCore/vue-hooks-plus/assets/48147837/188d5179-d675-4250-88a3-f43e7ec89a78)

**Comment by XiaoDaiGua-Ray** [comment]
可以描述更加清楚一点，并且可以贴出乱码的图。以便于更好的复现问题

**Comment by k983551019** [comment]
复制出来这玩意，
%3Ctemplate%3E%0A%20%20%3Cdemo1%20%2F%3E%0A%20%20%3Cdemo2%20%2F%3E%0A%20%20%3Cdemo3%20%2F%3E%0A%3C%2Ftemplate%3E%0A%0A%3Cscript%20lang%3D%22ts%22%20setup%3E%0A%20%20import%20%7B%20useRequest%20%7D%20from%20'vue-hooks-plus'%0A%20%20import%20%7B%20defineComponent%2C%20h%20%7D%20from%20'vue'%0A%20%20import%20%7B%20useFetchingPlugin%20%7D%20from%20'%40vue-hooks-plus%2Fuse-request-plugins'%0A%20%20import%20Demo3%20from%20'.%2Fdemo3.vue'%0A%0A%20%20const%20demo1%20%3D%20defineComponent(%7B%0A%20%20%20%20setup%3A%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20function%20getUsername(params%3A%20%7B%20desc%3A%20string%20%7D)%3A%20Promise%3Cstring%3E%20%7B%0A%20%20%20%20%20%20%20%20return%20new%20Promise(resolve%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20setTimeout(()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20resolve(%60vue-hooks-plus%20%24%7Bparams.desc%7D%60)%0A%20%20%20%20%20%20%20%20%20%20%7D%2C%201000)%0A%20%20%20%20%20%20%20%20%7D)%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20const%20%7B%20data%2C%20loading%20%7D%20%3D%20useRequest(%0A%20%20%20%20%20%20%20%20()%20%3D%3E%20getUsername(%7B%20desc%3A%20'good'%20%7D)%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20fetchingKey%3A%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20'one'%0A%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20onFetching%3A%20(current%3A%20any%2C%20record%3A%20any)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log(current)%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log(record)%0A%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20isFetching%3A%20(v%3A%20any)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log(v)%0A%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%5BuseFetchingPlugin%5D%2C%0A%20%20%20%20%20%20)%0A%20%20%20%20%20%20return%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20return%20h('div'%2C%20%7B%7D%2C%20%5B%0A%20%20%20%20%20%20%20%20%20%20h('h3'%2C%20'demo1')%2C%0A%20%20%20%20%20%20%20%20%20%20h('div'%2C%20null%2C%20loading.value%20%3F%20'loading'%20%3A%20data.value)%2C%0A%20%20%20%20%20%20%20%20%5D)%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%7D)%0A%0A%20%20const%20DemoGlobal%20%3D%20defineComponent(%7B%0A%20%20%20%20setup%3A%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20function%20getUsername(params%3A%20%7B%20desc%3A%20string%20%7D)%3A%20Promise%3Cstring%3E%20%7B%0A%20%20%20%20%20%20%20%20return%20new%20Promise(resolve%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20setTimeout(()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20resolve(%60vue-hooks-plus%20%24%7Bparams.desc%7D%60)%0A%20%20%20%20%20%20%20%20%20%20%7D%2C%202000)%0A%20%20%20%20%20%20%20%20%7D)%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20const%20%7B%20data%2C%20loading%20%7D%20%3D%20useRequest(%0A%20%20%20%20%20%20%20%20()%20%3D%3E%20getUsername(%7B%20desc%3A%20'good'%20%7D)%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%2F%2F%20manual%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20fetchingKey%3A%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20'two'%0A%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20onFetching%3A%20(current%3A%20any%2C%20record%3A%20any)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log(current)%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log(record)%0A%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%5BuseFetchingPlugin%5D%2C%0A%20%20%20%20%20%20)%0A%0A%20%20%20%20%20%20%2F%2F%20run()%0A%20%20%20%20%20%20return%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20return%20h('div'%2C%20%7B%7D%2C%20%5B%0A%20%20%20%20%20%20%20%20%20%20h('h3'%2C%20'demo2')%2C%0A%20%20%20%20%20%20%20%20%20%20h('div'%2C%20null%2C%20loading.value%20%3F%20'loading'%20%3A%20data.value)%2C%0A%20%20%20%20%20%20%20%20%5D)%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%7D)%0A%0A%20%20const%20demo2%20%3D%20defineComponent(%7B%0A%20%20%20%20setup%3A%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20return%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20return%20h(DemoGlobal)%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%7D)%0A%3C%2Fscript%3E%0A

**Comment by NelsonYong** [comment]
@k983551019 已经解决

**Comment by Husky-Yellow** [comment]
> @k983551019 已经解决

您好，是什么问题？我这边也在排查，也参考了其他 vitepress 的项目，没查出来问题。
