### ISSUE TITLE
是否考虑基于中间件开发模式？

### ISSUE THREAD

**Issue by l246804** [InhiblabCore/vue-hooks-plus#171]
### Description

现在的 `useRequest` 是基于插件系统设计的，但实际上插件执行流与正常的网络请求流不是很符合，而类似 `Koa` 的洋葱圈模型我感觉会更适合这种状态管理库，也可以更好地组合拆解 `useRequest` 的各种功能。

### Suggested solution

更改插件系统为洋葱圈模型，拆分内置功能中间件，支持创建干净无污染的 `useRequest`。

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by NelsonYong** [comment]
<img width="592" alt="iShot_2023-09-30_09 39 54" src="https://github.com/InhiblabCore/vue-hooks-plus/assets/43402341/a476140e-3ee7-4043-99ae-3ca8d46d0778">
<img width="375" alt="iShot_2023-09-30_09 40 03" src="https://github.com/InhiblabCore/vue-hooks-plus/assets/43402341/02945444-6ec9-4d86-9970-938ae4ad35ab">

下一个 alpha 版本会支持 @l246804

**Comment by l246804** [comment]
前段时间基于你的插件方式和 `SWR` 开发了个请求管理库，想和你深入探讨下对请求管理库的使用和实现方式，有交流群吗。

**Comment by NelsonYong** [comment]
@l246804 暂时没有交流群，你可以添加我的 qq 号，我的主页有 qq 邮箱，信息一致

**Comment by NelsonYong** [comment]
@l246804 `v1.8.6` beta version
docs: https://inhiblabcore.github.io/docs/hooks/useRequest/middleware/

**Comment by l246804** [comment]
qq搜索不到。。。
