### ISSUE TITLE
如何在nuxt中使用ssr功能？

### ISSUE THREAD

**Issue by sukbearai** [InhiblabCore/vue-hooks-plus#175]
### Description

`const { runAsync } = useRequest(getTodo, {
  manual: true,
})

const { data: todos } = await useAsyncData('todos', () => runAsync({ id: 2 }))

const online = useOnline()
const text = 'hello world'`

### Suggested solution

怎么实现ssr呢？

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by NelsonYong** [comment]
@sukbearai ，正常引入使用即可。当然了，它并不是完全在服务端，只是说支持在 ssr 项目中使用

**Comment by NelsonYong** [comment]
因为像 useRequest 会有 effect 这些方法，显然是不支持在服务端渲染的时候使用，但支持在 ssr 项目中的客户端渲染的时候生效使用。
