### ISSUE TITLE
[useRequest] `onError` not catching `onBefore` error

### ISSUE THREAD

**Issue by Airkro** [InhiblabCore/vue-hooks-plus#177]
### Describe the bug

throw an error in `onBefore`,

`onError` callback is not fire...

### Steps to reproduce

```vue
<template>
  <button @click="run">run</button>
  <div>data: {{ JSON.stringify(data) }}</div>
  <div>error: {{ error?.message }}</div>
</template>

<script setup>
import { useRequest } from 'vue-hooks-plus';

const { data, error, run } = useRequest(async () => {
  // return anything here
}, {
  manual: true,
  onBefore() {
    // do something then
    throw new Error('example'); // remove this line everything will fine
  },
  onSuccess(result) {
    console.log('okay:', result)
  },
  onError(error) {
    console.error('inner', error);  // this line will not run, can't catch `Error: example`
  },
});
</script>

```

### System Info

```shell
vue-hooks-plus: 1.8.6
vue: 3.3.x
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by XiaoDaiGua-Ray** [comment]
hi.
In response to your question, I have not repeated it.

<img width="1028" alt="image" src="https://github.com/InhiblabCore/vue-hooks-plus/assets/51957438/300780a3-21ce-4a50-8ab9-25ab1207d10f">
<img width="1408" alt="image" src="https://github.com/InhiblabCore/vue-hooks-plus/assets/51957438/6d68f5e7-31e2-4125-acab-f82b214aacba">

**Comment by XiaoDaiGua-Ray** [comment]
hi.
In response to your question, I have not repeated it. Can you provide more code details?

<img width="1412" alt="image" src="https://github.com/InhiblabCore/vue-hooks-plus/assets/51957438/f2524066-ccd7-41df-b1d0-4562c4659964">

**Comment by Airkro** [comment]
[reproduce playground](https://play.vuejs.org/#eNqNU8Fu2zAM/RXCF6dAYmEoMGxpWmQdetgO29Dt6ENdm4nVyJImUU2GIP8+Sk5SJ9uKXQyb74nvkU/eZh+sLZ4DZtNsRthZVRHelBpg9hiIjIZ5rWS9ui4zF3SZ3fBzJnqIaTMxOMOfvnbSEnikYLkiO2scwRaCx3v8GdAT7GDhTAc5a05aY1Z+YlXweTxeG82ELaBzxo2BpZh9PTg8qvwvXcPoAq5vYLsbwzY67SodKjUFcgHHsWD0LS6MQ+YlAoAQ0BjwpkNqpV4Ctch6EaHWmTVoXMNdVB3luKl4IswvriJht2/Yg8nYsWm0axQWqTrKpdbo8nHv/uIqibKaByU1wloqBdpQnGoMdaVz4ifVLTyk3lPYCz8cZHfRAe9wASe6Z6qGoxjIvqIKax4aUprQB8gaMcI+NI4rG2d9YpOussWTN5pvRRIt94Avs+lh/DI7jTBCZdYSWT8VImi7Wha16cQpa/6meFe8FY30JJ68kLrBTYGe1cos7Xrf+LRb3WhmNKjksys0ktC2E3OmCR6MZIeTxnTzy+KyeN+3HpS5ezd55JQ9usI60/yhJRh5RjdxyG4cuv/VPjs21D+DTjxE+RQy759XTp4jXcjl2cJ5dVYqdF8tSY78ZPGVUmb9OdWOlz6dabFe/aX+5Df9TN8cJmeD+alyS6Qevvv+BTf8fgQ70wS1z+If4D3ydQzRY0+7Dbph2wNecvsp3R/+9374uw2h9oehotGXPy3l8fGV0V/s8raPW9z9Bis5n3A=)

**Comment by XiaoDaiGua-Ray** [comment]
I think you're using it the wrong way, 'async () => {}' seems to be an invalid parameter, so the code doesn't work as expected.

<img width="1728" alt="image" src="https://github.com/InhiblabCore/vue-hooks-plus/assets/51957438/3ec38a82-2c89-4a5a-bd84-c61e28f444a3">

**Comment by Airkro** [comment]
It is just an example, and there is nothing wrong with `async () => {}`. an async function will return `Promise<void>`, it will work fine.

If you still don't understand, I make a better [example](https://play.vuejs.org/#eNqNU01v2zAM/SuEL06AxMJQYNjSNMs69LAe2qHd0Ye6NhOrkSVPH/lA4P8+SkpTJ92GXQybfCTf46P3yde2zdYOk0kytdi0orA4yyXA9NlZqyTMS8HL1VWeaCfzZEbPKYupCKv4elYVtpjAfg+3j/d3mbGayyVf7AY+PoSumzKPOsJRa6UDPrx9yRo0plhiDzllPTL0aUrNWwsGrWspwptWaQt7cAYf8JdDY6GDhVYNpCRmXCu1MuNWOJNe+vpSSULswRMaxakjIClUdNXrMSjMTpYwGMLVDPaeL2OgaaaWUMidrUkX1Kgxl90oAppCukJMwGqHIx9Q8hoXSiM1CYDQo1JgVIOxga2RKPmMrbXagMQN3HhKgxS3BanGdHgZJzdqjYTiBgSXCLhGfWCx4ULAgoK+U3eY/OjKklY50GicsEcCXr0SmAm1HKRqVewmKamPmH55JBG28642RAcplxI1VUfQZRD3xi+Qksr61Y6gLGRq6WnLGp5C7wkcBD69ju2G5M+URXvJ2GSURG/HTdFmL0ZJOsxAJT8kTJ7Q6URyeXJqtk/lSW1tayaMOdmullmpGnaKmn/IPmUf6dCMZS+GcVnhNkND0/IkbOLQ+LRbWUlCVCj4WmcSLZNtw+YEYyTW8gbHlWrmF9lF9jm27oWpezN+Jq8N6qzVqno3i1GGzB1rJDYa9f/OPivrzz9LnXDw44MF5ACt3BqyecGXZwun1bVcoL5vLaczOFl8IYTa3IbY8fRDTY3l6g/xF7ONmn7Q4XlmPf220Eu0MX3zeIdbej8mG1U5cfDiL8kHpBN1nmOEXTtZEe0eLrD9Hu6Hfp6f5mZrUZpXUZ7o238Q/Pj2D+lvdGnbxy12vwFr4MwG)

**Comment by XiaoDaiGua-Ray** [comment]
Got it.

It is a manual error thrown in the 'onBefore' configuration item that interrupts the entire code flow.

It seems to be a problem, which will be solved later in the discussion.

**Comment by XiaoDaiGua-Ray** [comment]
<img width="1219" alt="image" src="https://github.com/InhiblabCore/vue-hooks-plus/assets/51957438/01e00196-1076-4a7a-9e99-f0aa39253aad">
<img width="1411" alt="image" src="https://github.com/InhiblabCore/vue-hooks-plus/assets/51957438/7c3a0384-0784-4fc6-bf87-f37277b002d8">

**Comment by NelsonYong** [comment]
@XiaoDaiGua-Ray @Airkro  Done.

version: `v1.8.7`
