### ISSUE TITLE
如何处理多个请求？

### ISSUE THREAD

**Issue by yyqxjwxy** [InhiblabCore/vue-hooks-plus#181]
### Description

看文档只有 只能使用useFetchs处理多个相同 URL 携带不同参数的请求，如果我想一次性请求多个不同url 的请求怎么办

### Suggested solution

希望可以提供一个数组参数放入多个不同的请求

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by XiaoDaiGua-Ray** [comment]
能否提供一个demo，描述一下你的需求呢？

**Comment by XiaoDaiGua-Ray** [comment]
这个似乎与 `useRequest` 的设计思路相悖。暂时没有这么支持的计划。

**Comment by NelsonYong** [comment]
@yyqxjwxy 如果你想实现这样的功能，可以提供一下思路给你。可以使用数组管理 request , 比如 `[{ requestFn,requestKey, requestParams }]`, 将 requestKey 包含在循环中，第一种方法、可以在里面使用 响应式对象去管理这些状态，当然了，功能只有简单的 loading 这些状态。第二， vue 中的 hook 并没有顶层 hook 的概念，可以在循环中使用 useRequest 管理的请求。cc @XiaoDaiGua-Ray

**Comment by NelsonYong** [comment]
useRequest 会比较考虑通用性，所以暂时不考虑实现这种场景。
