### ISSUE TITLE
使用插件修改data返回数据的时候，ts类型推断没有改变

### ISSUE THREAD

**Issue by Wong-Harry** [InhiblabCore/vue-hooks-plus#183]
### Description

我在useFormatterPlugin中修改了data的返回格式化，但是我在外部调用data的时候，还是提示默认推断

默认的推断类型有如下
![image](https://github.com/InhiblabCore/vue-hooks-plus/assets/39816603/a0b04326-0812-4931-826d-e32443e400dc)

useFormatterPlugin插件代码
![image](https://github.com/InhiblabCore/vue-hooks-plus/assets/39816603/68e23ec6-1f26-4a14-8636-15aa028a0209)

useRequest代码
![image](https://github.com/InhiblabCore/vue-hooks-plus/assets/39816603/aad77fac-6cc3-4527-b4c7-3d4ff4eb3475)

### Suggested solution

后续是否有方法，将类型推断返回正确呢

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by XiaoDaiGua-Ray** [comment]
该问题是一个这边暂时一直没有很好解决的一个问题。并且，在设计 `useRequest` 之处也有过考虑 `forrmater` 的情况，但是综合总体后，还是建议使用 [`useFormatResult`](https://inhiblabcore.github.io/docs/hooks/useFormatResult/) 方法，也可以更好的类型提示。

**Comment by XiaoDaiGua-Ray** [comment]
在文档也有所提及为什么没有实现该插件的原因：
<img width="785" alt="image" src="https://github.com/InhiblabCore/vue-hooks-plus/assets/51957438/bbb3704c-fc44-433f-8362-f099b1e6d47b">

**Comment by NelsonYong** [comment]
@Wong-Harry 因为 useRequest 的设计是由一个基础功能的容器加载插件实现的，所以想通过想通过 format 去改变类型，会被内部类型造成很多的破坏，经过权衡得出，第一、你可以使用 [useFormatResult](https://inhiblabcore.github.io/docs/hooks/useFormatResult/) 去实现类型的格式化，第二、可以在 请求函数内部将数据格式化使用。

其次，默认的推断类型可能存在 undefined 是符合预期的，因为对于远程数据，一开始就是处于一个 undefined 状态，这也是为了开发者在使用的过程中规避一些风险。
