### ISSUE TITLE
导致lodash全部引入（Resulting in the introduction of all lodash）

### ISSUE THREAD

**Issue by zhangziyi123** [InhiblabCore/vue-hooks-plus#184]
### Describe the bug

安装vue-hooks-plus(v1.8.8)后，项目打包进行包分析，发现lodash被全部引入，大小接近100kb，gzip压缩后为49.32kb；如果去掉vue-hooks-plus再打包进行包分析，就没有lodash。(After installing Vue books plus, the project was packaged for package analysis and it was found that lodash was fully introduced, with a size close to 100kb. After gzip compression, it was 49.32kb; If we remove Vue books plus and package it for package analysis, there will be no lodash.)

### System Info

```shell
win10 vscode
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NelsonYong** [comment]
@zhangziyi123 感谢你的反馈，经过排查，大概率是在从 lodash 导入类型的时候写法有误，导致打包的时候进行 tree shaking 失败。

**Comment by XiaoDaiGua-Ray** [comment]
正在排查。

**Comment by XiaoDaiGua-Ray** [comment]
你好，经过排查发现，并未全部构建所有的 `lodash` 依赖在 `vue-hooks-plus` 中。

之所以会构建出如此大体积的 `lodash` 依赖包，是因为 `vue-hooks-plus` 中依赖的该库的方法在内部本身依赖了很多依赖，所以导致体积如此大。

感谢你的提出的意见，这块问题，后续我们会持续跟进改进 `lodash` 依赖体积大问题。

**Comment by zhangziyi123** [comment]
可否加我qq好友，可以一起再核对一下这个问题，方便的话加一下我哈  QQ: 2928916431

**Comment by XiaoDaiGua-Ray** [comment]
好的。

**Comment by kevinlvhsl** [comment]
问题最后在哪个版本解决的？
