### ISSUE TITLE
关于useFetchs返回值问题

### ISSUE THREAD

**Issue by MangMax** [InhiblabCore/vue-hooks-plus#193]
### Describe the bug

请问一下为什么useFetchs返回数据要用DeepReadonly，而useRequest只是最外面设置Readonly，这导致很多时候赋值给相同类型的对象但是如果被加上readonly的话类型就不一样报错了，还需要自己手动处理一遍，请问一下最佳实践是怎么样子的

### System Info

```shell
win11 
Edge 124.0.2478.51
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NelsonYong** [comment]
@MangMax 你的意思是，当你想 const name =  ref<string>() name.ref = fetchs[0].data.name  会报类型错误吗？因为被 deepreadonly 了。

**Comment by NelsonYong** [comment]
@MangMax 请留意版本更新，我会在近两天将这个问题修复

**Comment by MangMax** [comment]
是这个意思，感谢

**Comment by NelsonYong** [comment]
@MangMax 已经更新 `v1.9.0`
