### ISSUE TITLE
文档地址挂了

### ISSUE THREAD

**Issue by yqiuwen** [InhiblabCore/vue-hooks-plus#195]
### Describe the bug

https://inhiblab-core.gitee.io/docs/hooks 地址无法访问

### System Info

```shell
https://inhiblab-core.gitee.io/docs/hooks 地址无法访问
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Roywhite** [comment]
地址改了：https://inhiblabcore.github.io/docs/hooks/guide/

**Comment by NelsonYong** [comment]
@yqiuwen gitee 国内镜像确实挂了，我需要排查一下，可以先用上面的 github io，它现在对国内支持的也不错。

**Comment by NelsonYong** [comment]
@#%😑 gitee

**Comment by NelsonYong** [comment]
@yqiuwen gitee page 服务正在维护
<img width="778" alt="image" src="https://github.com/InhiblabCore/vue-hooks-plus/assets/43402341/62356a06-75b5-418e-92f7-e5ba1048d093">
