### ISSUE TITLE
Difference / Imporovement compared with vueuse

### ISSUE THREAD

**Issue by colgin** [InhiblabCore/vue-hooks-plus#20]
Hi, thank you for provide such awesome library for vue ecosystem. After reading part of doc and the codebase, I still can't figure out the difference between vueuse.

In personal opinion, the most difference is the api design; 
In vueuse

```js
export interface UseToggleOptions<Truthy, Falsy> {
  truthyValue?: MaybeComputedRef<Truthy>
  falsyValue?: MaybeComputedRef<Falsy>
}
export declare function useToggle<Truthy, Falsy, T = Truthy | Falsy>(
  initialValue: Ref<T>,
  options?: UseToggleOptions<Truthy, Falsy>
): (value?: T) => T
export declare function useToggle<
  Truthy = true,
  Falsy = false,
  T = Truthy | Falsy
>(
  initialValue?: T,
  options?: UseToggleOptions<Truthy, Falsy>
): [Ref<T>, (value?: T) => T]
```

the first argument can be a ref variable or a normal variable.

In vue-hooks-plus, 
```js
const [state, { toggle, set, setLeft, setRight }] = useToggle(defaultValue?: boolean);
const [state, { toggle, set, setLeft, setRight }] = useToggle<T>(defaultValue: T);
const [state, { toggle, set, setLeft, setRight }] = useToggle<T, U>(defaultValue: T, reverseValue: U);
```
the first argument should be a normal variable, and the return value of useToggle is stable as well.

vueuse also make `window`, `document`, `navigator`, `location` configuable, see [_configureable](https://github.com/vueuse/vueuse/blob/main/packages/core/_configurable.ts), which can be used in some special cases.

So, it seems that vue-hooks-plus is another "simple" implementation of vueuse in most cases, right?

BTW,  I would appliciated it if you can give more descriptive example to respond to https://github.com/InhiblabCore/vue-hooks-plus/issues/10#issuecomment-1232807931

**Comment by NelsonYong** [comment]
Thanks for your support for ` vue-hooks-plus`  library！

Many people ask similar questions,  what is the different with the `vueuse`？

As you say the api is different, I think more about the applicability of the business,It was originally designed to solve the pain points of my business.

For instance 👇

- the useFetch and useAxios in vueuse didn't help me very much
- vueuse may not consider enough at the business level that the API cannot cover my needs

The vuesue is a pretty excellent project.
In terms of request I developed `useRequest` combined with swr. It contains great ✨ features. 👇

- debounce
- throttle
- loadingDelay
- polling
- fetchs
- ready
- refreshDeps
- refreshOnWindowFocus
- retry
- custom plugin

```typescript
import { useRequest } from 'vue-hooks-plus'

  function getUsername(params: { desc: string }): Promise<string> {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(`vue-hooks-plus ${params.desc}`)
      }, 1000)
    })
  }

  const { data, loading, params } = useRequest(() => getUsername({ desc: 'good' }))

```

Simple to use, powerful, and able to manage the cache status 💪  [ try it ](http://43.138.187.142:9000/vue-hooks-plus/docs/useRequest/guide/) quickly solve your business problems and I think it is the biggest difference from vueuse.

I will also use react, I am familiar with the state of react and combined with vue, I think the two are very similar, because vueuse is also borrowed from react-use, so some simple functions are similar, but some internal ideas or some complex functions will be redefined according to the developer. 

Understand the difference between the two, and hope you can get useful information from `vue-hooks-plus`. 

🏷️  difference <i>tips</i>

- api
- request
- function quantity

[juejin tells you ](https://juejin.cn/post/7130813191902199844)

**Comment by NelsonYong** [comment]
> Hi, thank you for provide such awesome library for vue ecosystem. After reading part of doc and the codebase, I still can't figure out the difference between vueuse.
> 
> In personal opinion, the most difference is the api design; In vueuse
> 
> ```js
> export interface UseToggleOptions<Truthy, Falsy> {
>   truthyValue?: MaybeComputedRef<Truthy>
>   falsyValue?: MaybeComputedRef<Falsy>
> }
> export declare function useToggle<Truthy, Falsy, T = Truthy | Falsy>(
>   initialValue: Ref<T>,
>   options?: UseToggleOptions<Truthy, Falsy>
> ): (value?: T) => T
> export declare function useToggle<
>   Truthy = true,
>   Falsy = false,
>   T = Truthy | Falsy
> >(
>   initialValue?: T,
>   options?: UseToggleOptions<Truthy, Falsy>
> ): [Ref<T>, (value?: T) => T]
> ```
> 
> the first argument can be a ref variable or a normal variable.
> 
> In vue-hooks-plus,
> 
> ```js
> const [state, { toggle, set, setLeft, setRight }] = useToggle(defaultValue?: boolean);
> const [state, { toggle, set, setLeft, setRight }] = useToggle<T>(defaultValue: T);
> const [state, { toggle, set, setLeft, setRight }] = useToggle<T, U>(defaultValue: T, reverseValue: U);
> ```
> 
> the first argument should be a normal variable, and the return value of useToggle is stable as well.
> 
> vueuse also make `window`, `document`, `navigator`, `location` configuable, see [_configureable](https://github.com/vueuse/vueuse/blob/main/packages/core/_configurable.ts), which can be used in some special cases.
> 
> So, it seems that vue-hooks-plus is another "simple" implementation of vueuse in most cases, right?
> 
> BTW, I would appliciated it if you can give more descriptive example to respond to [#10 (comment)](https://github.com/InhiblabCore/vue-hooks-plus/issues/10#issuecomment-1232807931)

Thanks for your issue 😃.

**Comment by colgin** [comment]
> Thanks for your support for ` vue-hooks-plus` library！
> 
> Many people ask similar questions, what is the different with the `vueuse`？
> 
> As you say the api is different, I think more about the applicability of the business,It was originally designed to solve the pain points of my business.
> 
> For instance 👇
> 
> * the useFetch and useAxios in vueuse didn't help me very much
> * vueuse may not consider enough at the business level that the API cannot cover my needs
> 
> The vuesue is a pretty excellent project. In terms of request I developed `useRequest` combined with swr. It contains great ✨ features. 👇
> 
> * debounce
> * throttle
> * loadingDelay
> * polling
> * fetchs
> * ready
> * refreshDeps
> * refreshOnWindowFocus
> * retry
> * custom plugin
> 
> ```ts
> import { useRequest } from 'vue-hooks-plus'
> 
>   function getUsername(params: { desc: string }): Promise<string> {
>     return new Promise((resolve, reject) => {
>       setTimeout(() => {
>         resolve(`vue-hooks-plus ${params.desc}`)
>       }, 1000)
>     })
>   }
> 
>   const { data, loading, params } = useRequest(() => getUsername({ desc: 'good' }))
> ```
> 
> Simple to use, powerful, and able to manage the cache status 💪 [ try it ](http://43.138.187.142:9000/vue-hooks-plus/docs/useRequest/guide/) quickly solve your business problems and I think it is the biggest difference from vueuse.
> 
> I will also use react, I am familiar with the state of react and combined with vue, I think the two are very similar, because vueuse is also borrowed from react-use, so some simple functions are similar, but some internal ideas or some complex functions will be redefined according to the developer.
> 
> Understand the difference between the two, and hope you can get useful information from `vue-hooks-plus`.
> 
> 🏷️ difference tips
> 
> * api
> * request
> * function quantity
> 
> [juejin tells you ](https://juejin.cn/post/7130813191902199844)

useRequest is pretty cool!
