### ISSUE TITLE
@vue-hooks-plus/resolvers 自动导入版本不匹配

### ISSUE THREAD

**Issue by huxiguo** [InhiblabCore/vue-hooks-plus#205]
### Describe the bug

使用@vue-hooks-plus/resolvers自动导入，版本不匹配，类型提示丢失

### System Info

```shell
mac v2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by XiaoDaiGua-Ray** [comment]
能否提供一个详细的报错截图或者报错信息呢？

**Comment by huxiguo** [comment]
![Uploading Snipaste_2024-05-20_10-07-52.png…]()

**Comment by huxiguo** [comment]
![Uploading Snipaste_2024-05-20_10-07-52.png…]()

**Comment by huxiguo** [comment]
<img width="1443" alt="Snipaste_2024-05-20_10-07-52" src="https://github.com/InhiblabCore/vue-hooks-plus/assets/71011744/5ba12e5b-4ae4-47cf-a205-479cae786f94">

**Comment by XiaoDaiGua-Ray** [comment]
暂时没有查看出具体的错误定位。还是希望你制作一个在线的最小复现，否则这边没有更好的办法帮助到你。

**Comment by NelsonYong** [comment]
@huxiguo 我刚刚看了一下，最新版的 vue-hooks-plus 没有发现和自动导入插件有冲突的地方。我使用和你用法一致。
可以尝试重新跑一下项目，或者重新安装一下依赖包。
<img width="694" alt="image" src="https://github.com/InhiblabCore/vue-hooks-plus/assets/43402341/55c88e77-fa0c-4ec3-bfab-fe6f4ba3e405">

**Comment by NelsonYong** [comment]
可以尝试安装最新版的 vue-hooks-plus `v2.1.0` 以及 resolver `1.2.4`

**Comment by huxiguo** [comment]
ok thanks
