### ISSUE TITLE
useRequest 在uniapp中使用 轮询 安卓app里面使用cancel 无法取消轮询，其他端都可以，有遇到过的大佬吗？

### ISSUE THREAD

**Issue by huxiguo** [InhiblabCore/vue-hooks-plus#206]
### Describe the bug

useRequest 在uniapp中使用 轮询 安卓app里面使用cancel 无法取消轮询，其他端都可以，有遇到过的大佬吗？

### System Info

```shell
mac v2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NelsonYong** [comment]
@huxiguo 可以尝试一下使用其他机型或者不同的安卓系统验证一下，排查一下是安卓app 的影响还是测试机型本身导致的问题。
