### ISSUE TITLE
请教一下cancel相关问题

### ISSUE THREAD

**Issue by Sharang-heng** [InhiblabCore/vue-hooks-plus#207]
### Describe the bug

当页面销毁时，应该注销网络的回调，所以我想在页面unmounted阶段都调用一次cancel，看了其他人提过一次issue，你们不是通过abort去中断取消请求，而是比较count
![image](https://github.com/InhiblabCore/vue-hooks-plus/assets/69613396/ea157ac8-f23b-4762-a008-833ac180922a)
想请教一下，调用cancel你们返回一个new Promise(() => {})就应该能预防内存泄漏的问题了吧？那如果我使用的是runAsync也是同样的道理吗，然后就是有没有考虑说以后会在页面销毁时自动调用cancel，这样就不需要每个页面都在unmounted写一次cancel了
感谢~

### System Info

```shell
version：2.1.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NelsonYong** [comment]
@Sharang-heng 目前已经存在当 unmounted 的时候进行 cancel https://github.com/InhiblabCore/vue-hooks-plus/blob/2679e6e4484ecbfdbb63fbee8d2a6145e3268db2/packages/hooks/src/useRequest/useRequestImplement.ts#L102

**Comment by NelsonYong** [comment]
@Sharang-heng 目前你的业务场景中存在 unmounted 的时候不手动cancel 导致请求没被 cancel 的问题吗
