### ISSUE TITLE
@vue-hooks-plus/resolvers 与vue-hooks-plus@2.1.0 不匹配，导致npm安装时需要 --force

### ISSUE THREAD

**Issue by vaseala** [InhiblabCore/vue-hooks-plus#208]
### Description

直接执行安装报下面的错：

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @vue-hooks-plus/resolvers@1.2.4
npm ERR! Found: vue-hooks-plus@2.1.0
npm ERR! node_modules/vue-hooks-plus
npm ERR!   vue-hooks-plus@"^2.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue-hooks-plus@"^1.5.2" from @vue-hooks-plus/resolvers@1.2.4
npm ERR! node_modules/@vue-hooks-plus/resolvers
npm ERR!   dev @vue-hooks-plus/resolvers@"^1.2.4" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: vue-hooks-plus@1.9.0
npm ERR! node_modules/vue-hooks-plus
npm ERR!   peer vue-hooks-plus@"^1.5.2" from @vue-hooks-plus/resolvers@1.2.4
npm ERR!   node_modules/@vue-hooks-plus/resolvers
npm ERR!     dev @vue-hooks-plus/resolvers@"^1.2.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/***/.npm/_logs/2024-05-28T01_12_40_636Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/***/.npm/_logs/2024-05-28T01_12_40_636Z-debug-0.log

目前安装时需要 npm i --force

### Suggested solution

建议升级 @vue-hooks-plus/resolvers 对 vue-hooks-plus 依赖的版本

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by NelsonYong** [comment]
@vaseala 已更新至 `1.2.5`
