### ISSUE TITLE
点击clear按钮不生效

### ISSUE THREAD

**Issue by CoderFXJ** [InhiblabCore/vue-hooks-plus#21]
![image](https://user-images.githubusercontent.com/68853957/199938057-7aab5603-8ae5-445d-97c9-4dd1030d5b90.png)

**Comment by NelsonYong** [comment]
> ![image](https://user-images.githubusercontent.com/68853957/199938057-7aab5603-8ae5-445d-97c9-4dd1030d5b90.png)

已经解决，第一次可以清除，因为是采用watch去监听state，所以在第一次清除会赋值default对象
，第二次还是会赋予这个对象，所以地址是一致的，state没被watch所监听，所以采用 拷贝的方式赋值。

```
 const clear = () => (state.value = Object.assign({}, defaultState))
```
