### ISSUE TITLE
refreshDeps 和 pollingInterval同时使用，导致一直无限请求

### ISSUE THREAD

**Issue by zaxlct** [InhiblabCore/vue-hooks-plus#210]
### Describe the bug

```  
  refreshDeps: true,
  pollingInterval: 1000 * 60 * 5,
  pollingWhenHidden: false
```
refreshDeps 和pollingInterval同时使用，一直无限请求接口， pollingInterval设置的间隔时间无效

### System Info

```shell
"vue-hooks-plus": "^1.8.9"
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by XiaoDaiGua-Ray** [comment]
这边建议给一个最小复现呢？

**Comment by NelsonYong** [comment]
@zaxlct 目前已经修复，更新到了 `2.2.0` 版本。原因是，timeRef.value = setTimeout(xxxx) ,被 watchEffect 监听到了，一致循环的进行 refresh 操作。
