### ISSUE TITLE
lodash-es推荐

### ISSUE THREAD

**Issue by zhangziyi123** [InhiblabCore/vue-hooks-plus#211]
### Description

Lodash官方提供了ES Module版本的lodash： lodash-es, 给我们导入lodash模块，Tree Shaking就可以生效，其他没用到的代码打包的时候就可以自动移除掉了。
  

### Suggested solution

写法如下：
原来写法：import debounce from "lodash/debounce"
改后：import { debounce } from "lodash-es"
打包大小是差不多，就是写法上的区别，后者更方便一点。

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by NelsonYong** [comment]
@zhangziyi123 我会在近期将 lodash 改外 es

**Comment by NelsonYong** [comment]
@XiaoDaiGua-Ray help , 有空帮忙搞搞

**Comment by XiaoDaiGua-Ray** [comment]
okkk，今天抽空看看。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: YongGit ***@***.***&gt;
发送时间: 2024年6月28日 11:50
收件人: InhiblabCore/vue-hooks-plus ***@***.***&gt;
抄送: XiaoDaiGua-Ray ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [InhiblabCore/vue-hooks-plus] lodash-es推荐 (Issue #211)





 
@XiaoDaiGua-Ray help , 有空帮忙搞搞

**Comment by inhiblab** [comment]
lodash-es 会影响我当前 vitepress 的构建，麻了 @XiaoDaiGua-Ray @zhangziyi123

**Comment by inhiblab** [comment]
vitepress 内部会 require vhp，lodash-es 不支持 common js
