### ISSUE TITLE
gitee文档地址打不开了

### ISSUE THREAD

**Issue by 6313504** [InhiblabCore/vue-hooks-plus#212]
### Describe the bug

gitee文档地址打不开了

### Steps to reproduce

gitee文档地址打不开了

### System Info

```shell
gitee文档地址打不开了
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by XiaoDaiGua-Ray** [comment]
gitee官方对于gitee pages托管功能下线了，目前只有github pages托管稳定。建议上上魔法。

**Comment by 6313504** [comment]
能否在readme中放个github pages的地址



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月12日(周三) 下午3:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [InhiblabCore/vue-hooks-plus] gitee文档地址打不开了 (Issue #212)




 
gitee官方对于gitee pages托管功能下线了，目前只有github pages托管稳定。建议上上魔法。

**Comment by XiaoDaiGua-Ray** [comment]
其实可以这么进入文档。

<img width="1467" alt="image" src="https://github.com/InhiblabCore/vue-hooks-plus/assets/51957438/8f2c6e95-0097-439c-89e2-f6a2bd4e1522">

**Comment by NelsonYong** [comment]
文档会在近期优化 @6313504
