### ISSUE TITLE
IOS内嵌Vue页面时useTitle失效

### ISSUE THREAD

**Issue by Aaroneee** [InhiblabCore/vue-hooks-plus#219]
### Describe the bug

IOS内嵌H5页面使用useTitle("XXX")时IOS顶部Title不展示

### System Info

```shell
"vue-hooks-plus": "^2.2.0"
"vue": "^3.4.21"
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NelsonYong** [comment]
@Aaroneee 调查了一下，因为 ios 只会在首次执行的时候渲染 title，后续就不会对 title 进行监听。这个在业界有个 hack 的方式解决，通过 iframe。

**Comment by NelsonYong** [comment]
目前暂不考虑 ios 的这种场景兼容，可以使用 iframe hack 哈
