### ISSUE TITLE
useInterval 没有返回值

### ISSUE THREAD

**Issue by huxiguo** [InhiblabCore/vue-hooks-plus#220]
### Describe the bug

useInterval 返回值为undefined

### System Info

```shell
谷歌浏览器 vhookplus 2.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NelsonYong** [comment]
@huxiguo  我看了一下这个 hook 并没有提供 return value 给到外部使用，这是 一个 bug，我会在这几天更新一个优化包，会在里面包含这个 bug 的修复，感谢你的反馈。

**Comment by inhiblab** [comment]
已经修复
文档：https://inhiblabcore.github.io/docs/hooks/useInterval/index.html#%E4%BB%A3%E7%A0%81%E6%BC%94%E7%A4%BA

版本：`v2.2.1`
