### ISSUE TITLE
useRequest在Pinia Store中使用时会出现warning

### ISSUE THREAD

**Issue by sxcooler** [InhiblabCore/vue-hooks-plus#224]
### Describe the bug

代码如下（stores/demo.js）：
``` js
export const useHeaderFormStore = defineStore('demo', () => {
// ……

  function getData() {
    const { run } = useRequest(service, {
      manual: true,
      debugKey: 'service',
      onSuccess: (tmp) => {
        data.value = tmp
      },
      onError: (error) => {
        console.log(error?.message)
      },
      onBefore: () => {
        loading.value = true
      },
      onFinally: () => {
        loading.value = false
      }
    })
  
    run(params)
  }

// ……
}
```

请求的时候会报warning：
![image](https://github.com/user-attachments/assets/36b7dec4-7142-48c0-b519-458ea8f6c625)

我在文档中搜索了pinia，似乎只有全局请求状态插件那里有提到，但使用的是option风格，而我使用的是composition风格，不知道是否与次有关？

建议增加一个选项，在执行时不进行inject相关操作

### System Info

```shell
Windows 11 专业版 23H2 22631.3880
binary不知道填什么
Chrome 126.0.6478.127
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NelsonYong** [comment]
@sxcooler 提示很明显了，useRequest 依赖了一些 vue 原生的方法只能在 setup 中使用，在 pinia 中使用会让它丢失 scope 的 effect 。你应该在视图层中使用 useRequest，然后再把它的数据推入 store

**Comment by sxcooler** [comment]
> @sxcooler 提示很明显了，useRequest 依赖了一些 vue 原生的方法只能在 setup 中使用，在 pinia 中使用会让它丢失 scope 的 effect 。你应该在视图层中使用 useRequest，然后再把它的数据推入 store

我当然知道是为什么，但是inject对于一个request库来说并不是必须的，它用这个是为了能在vue模板中使用，而不是反过来“没有vue就不能做一个request库”

至于你说的“你应该……”，这涉及到代码组织的问题，这个我也不和你争论对错，只能说和这个issue关系不大。

**Comment by sxcooler** [comment]
或者这么说吧，绝大多数的状态管理，从古早的redux、mobx，再到这个pinia，都推荐在store中使用action来更新状态，有些甚至有专门的action定义文件，这样做的好处是当项目非常复杂的时候，不至于牵一发而动全身，免得有些复用较多的store会找不到在哪里更新的，进而导致意外的渲染刷新。

所以个人认为我这个需求是合理的，望作者考虑。

**Comment by NelsonYong** [comment]
@sxcooler 你尝试一下将这个手动调用的 useRequest 放在store最外层。我说说我的看法，我认为全局状态不应该依赖于这个和vue 视图相关的hook，而是存粹的async await 即可，因为你压根用不到它的其他功能。我还认为项目庞大更应该是拆分功能模块，在功能模块内维护着请求和数据。当然没有好坏，看个人取舍。

**Comment by sxcooler** [comment]
> @sxcooler 你尝试一下将这个手动调用的 useRequest 放在store最外层。我说说我的看法，我认为全局状态不应该依赖于这个和vue 视图相关的hook，而是存粹的async await 即可，因为你压根用不到它的其他功能。我还认为项目庞大更应该是拆分功能模块，在功能模块内维护着请求和数据。当然没有好坏，看个人取舍。

我最初被VueHook Plus吸引是因为您的这篇文章：[Vue3开发，或许你需要这样使用请求API](https://juejin.cn/post/7143488626955911181)
然后看到您都做好了封装也就尝试了一下，确实比较优雅。
然后主要是使用了防抖、节流之类的功能，虽然我也知道您用了lodash，自己做也不会太难，但是VueHookPlus封装好了用起来很方便，代码比较简洁。

您提到的拆分功能模块，这个我当然认同，我实际的场景是在同一个模块内的，有一个inline form，好几个页面都会复用，所以给它设计了一个store，大概是这样，感谢您抽出时间回复。
