### ISSUE TITLE
如何知道useRequest自动发起的请求是被什么触发的？

### ISSUE THREAD

**Issue by lyric-zemin** [InhiblabCore/vue-hooks-plus#225]
### Description

```js
const { data, loading } = useRequest(
  () => fn(),
  {
    refreshDeps: [dep],
    pollingInterval: 1000,
  },
)
```

如上，请求会被`polling`, `dep`, 以及第一次自动执行，如何在类似`onBefore`钩子中知晓请求是被如何触发的

### Suggested solution

添加内部请求标识或者可执行方法判断触发方

```js
const { data, loading, trigger, getTrigger } = useRequest(
  () => fn(),
  {
    refreshDeps: [dep],
    pollingInterval: 1000,
  },
)

console.log(trigger.value)
console.log(getTrigger ())
// dep
// polling ...
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by NelsonYong** [comment]
@lyric-zemin 我觉得在内部提供这样的标识不太可行，方便告知你需要有这样标识符的目的吗，或许我们可以探讨一下更佳的方案。

**Comment by lyric-zemin** [comment]
> @lyric-zemin 我觉得在内部提供这样的标识不太可行，方便告知你需要有这样标识符的目的吗，或许我们可以探讨一下更佳的方案。

感谢回复，现在存在一个需求，需要在轮询的时候，在接口增加一个入参作为标识 `fromPolling=1`

**Comment by NelsonYong** [comment]
@lyric-zemin 目前不打算增加对应的功能。如果是我，我会将请求变为 manual 手动请求，通过 watch 去监听 deps 和 useInterval 的方法去做轮询实现这个功能。
