### ISSUE TITLE
[BUG]: useRequest manual=false 时，loading 初始值不是false，而是 true

### ISSUE THREAD

**Issue by jianhao** [InhiblabCore/vue-hooks-plus#234]
### 遇到的问题
我通过useRequest请求数据，loading 初始值为true，导致页面loading无法正常显示。
代码如下：
```
  const { data, loading } = useRequest(() => getUsername({ desc: 'good' }), {
    debugKey: 'demo',
    initialData:"000"
  })

  console.log('初始状态', loading.value)
  // 监听 loading 状态变化
  watchEffect(() => {
    console.log('loading change:', loading.value);
  });
```
  
  loading 状态初始就为true, 正常流程应该是false => true => false.
  
  如果设置 manual=true， 通过run手动触发请求，则loading状态变化正常。
  
  ### 代码示意图
  manual 为false, 默认触发请求
<img width="1701" alt="image" src="https://github.com/user-attachments/assets/d4e34f0a-de05-4621-8291-551c6277cd2d">

manual 为 true, 手动触发请求
<img width="1745" alt="image" src="https://github.com/user-attachments/assets/26eb7293-17fa-4c6a-9594-11e9c9edba4b">

### 可调试代码链接
[问题demo](https://play.vuejs.org/#eNqNVkuP40QQ/istL5IzUmI7yWTJmMwgHnMABKyW5ZbDduyy3TN2t+luJxmiSHBDgARcEAJx5sKZE38n7JG/QLVfsbMzIxTFj3r1V19VdXtnvZPnzroAy7cWGrI8pRqulpyQRcjWV5xm8O/fv+52JBU0ZDwmbxO7frSJT0KqKdnvF64xXvKF2wmBryqQLNckpTy+XFpaLS2iQBc5almWC6nJjmyoDpLrKIJAD4ngH4uCawjJnkRSZMRGaLaB09oXCp7DFwUo3bUZJULcqlGeFgrNqx8hUcEDzQQnMejPFUiTziCnkmbKx1AhqMAnSkuT2P7MJ88wHFOwqERXZGeCECIRs+SEw6axGEhQIl0DuWyNiEntBctAFHowOOtpTIjSfvCyj5W8savgOAbL/uVZ47EfkrHnefX7vrzvm7QCwTF7xI/sD5vKDIksOFJy2WGoxtHNvsnajoUIbYw8bGC6LskoL2jqa1nAsBKGsCrij+AOHULIhF2LGWea0fR9BOAvLQS6tEqEiNPc2zL2icAVEOOgSqY2NbmIFJxUxAP78M3vhz++e/XtX/989bXdZuasaVpA6YURXv320+HHP9t+rIwPP/xy+P5nY9Fpp/7ivYUa7yDB1gT/tbXeqiDibeFWTVw3tL5LTW+vRHhXx81paBx9Mp7k29KPkJWQIciRxJAFdlpHI9Ygo1RsfJKwMAReizMqY8ZHWuQ+mXfCbEcqoaExH+dbMsX/Of5lvKKD8XyOPTK/wMuFNySeM61QN6tXLpgyCyuHyXQ2JMcLOsxbDxrcxhJLFo4CkQr0feKNPRhf1PpauEmYBhTtCUEKCq0Fr0l4fckn55NwejHpBahgzAyC9uLM33wExXRKvadRra+ZHqUQaZ88bWlq5JLFSU9xUoZZq8iQ6w0LdYLWXitNoAowPUaIBNejTS2feV4tLokYqZwG4BMuNpLmtUZLyhXOhuB+lTTyPJmpYYOlLztJ+Gjb1B0l56qeOWweXJDpu1LYEFtIZZjKBcN5k10UkZAZ7m4BTWEwNhzj/lEVzU9MGzaD0UVmKJ/B6oI+XJLzyWo+n1YDYmaiDunTCNdvYuaiIYGusB+Ksm3qKdTAkUzbriWM477pk4bak5oxnoBkupmeioCu9XFCvPKHteth7JekZe7IBcUTYg0n+LtxueAN+nb98X2x28iM5wXuzw/4nAzT/TTfNyqe47UT25+F45bx/3v4weEo7RX7Elt7fJR2M6VparYPky9miztkuStaQ6s6pEcZzZ0bJTh+U5QkLGsFnv947Fbxllb/JDSqpZVonSvfdYOQY4QQUraWDgft8jxz+w74yaG0e6NcxkPYOqDQoT6FEBaC0QqbLWLxCZRAZDlLQX6am2T6kDAxsfmwlHXOQPRJILi9R36jthXuZ3i+g1zD0mp1Grd00JX6+rNPYIvPrTITYZGi9SPK5+aLoTAYK7N3sTsQdseuRPtBySy2wgt1vcXRUk1SBmjJRmlf0v3eI6kf4U6d85bF/X+iA00I)

### Steps to reproduce

通过更改是否手动触发

### System Info

```shell
依赖的资源如下：
"vue": "https://play.vuejs.org/vue.runtime.esm-browser.js",
"vue/server-renderer": "https://play.vuejs.org/server-renderer.esm-browser.js",
"vue-hooks-plus": "https://cdn.jsdelivr.net/npm/vue-hooks-plus/dist/js/index.es.js"
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NelsonYong** [comment]
@jianhao 因为请求发起的时机比你打印初始状态的时候要早。原因是自动发起的请求时机比较早，在以前的旧版本中是在 mounted 的时候发起，而在现在的版本则是在 setup 的时候就发起了。
<img width="2593" alt="image" src="https://github.com/user-attachments/assets/bdd2c4bc-f507-4bbc-9566-c16630692ff1">

**Comment by NelsonYong** [comment]
手动请求子所以出现 false true false 是因为手动 run 的时机是在 mounted 中，比 setup 要慢，所以才能看到初始为 false

**Comment by NelsonYong** [comment]
https://github.com/InhiblabCore/vue-hooks-plus/blob/00dde9fb20a50fb80841569ccc719193c381c77e/packages/hooks/src/useRequest/useRequestImplement.ts#L96

**Comment by NelsonYong** [comment]
相关信息已经回复在 👆，如果有疑问可以重新 reopen 这个 issue 哈，感谢你提供的宝贵意见 🌹
