### ISSUE TITLE
useRequest轮询pollingInterval动态修改不起作用

### ISSUE THREAD

**Issue by coderlcb** [InhiblabCore/vue-hooks-plus#30]
```
  const { loading, run: runQueryData } = useRequest(
    () => queryData(),
    {
      manual: true,
      pollingInterval: generalStore.getPollingInterval,
      pollingWhenHidden: false,
      onSuccess: (res: any) => {
        if (res.data && res.data.length > 0) {
          chartsData.value = res.data;
        }
      },
    }
  );
```
修改pinia后无效，直接传入组件无效，是不是手动的问题

**Comment by NelsonYong** [comment]
轮训 pollingInterval 完全受 run 控制无论是自动还是手动,在`useRequest` 的 [35行](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/packages/hooks/src/useRequest/plugins/usePollingPlugin.ts#L35)，如果是手动，完全受用户可控。需要通过监听  `generalStore.getPollingInterval` 这个getter 改变，再调用 `run` 方法才能使其获取最新的值.

如果是自动模式，则需要将 `generalStore.getPollingInterval` 作为依赖性传入  refreshDeps 中，它才会根据依赖刷新请求以此获取最新的值。

**Comment by NelsonYong** [comment]
它是在请求 `onFinally` 里面的 pollingInterval 并没有加监听，需要用户重新发起请求，pollingInterval才会更新。由于需要将其和refreshDeps做区分才会如此设计。

**Comment by coderlcb** [comment]
> refreshDeps

懂了，我也是想到了监听store的state，却忘了之前用ahook有个依赖刷新，还以为只有react hook 才有依赖数组这东西

**Comment by NelsonYong** [comment]
依赖数组不行吗 @coderlcb

**Comment by coderlcb** [comment]
> 它是在请求 `onFinally` 里面的 pollingInterval 并没有加监听，需要用户重新发起请求，pollingInterval才会更新。由于需要将其和refreshDeps做区分才会如此设计。
```
 const { loading, run: runQueryMarketData } = useRequest(
    () => queryMarketData(),
    {
      manual: true,
      pollingInterval: generalStore.pollingInterval,
      pollingWhenHidden: false,
      onSuccess: (res: any) => {
        if (res.data && res.data.length > 0) {
          chartsData.value = res.data;
        }
      },
    }
  );
  watch(
    () => generalStore.pollingInterval,
    (newValue) => {
      console.log(newValue);
      runQueryMarketData();
    }
  );
```
好像还是有点问题，我还是手动模式，监听了`generalStore.pollingInterval`的变化再调用，pollingInterval的值还是无效

**Comment by coderlcb** [comment]
> 依赖数组不行吗 @coderlcb

自动的话依赖数组也没用

**Comment by NelsonYong** [comment]
如果这样也不行，建议将其包裹在一个函数内进行调用，具体可以参考use-fetchs 的做法 @coderlcb

**Comment by NelsonYong** [comment]
如果可以，希望能给出一个在线例子我进行调试

**Comment by coderlcb** [comment]
> 如果这样也不行，建议将其包裹在一个函数内进行调用，具体可以参考use-fetchs 的做法 @coderlcb

我看看

**Comment by NelsonYong** [comment]
vue 不同于 react ,不需要在最顶层

**Comment by coderlcb** [comment]
> vue 不同于 react ,不需要在最顶层

啊这。。

**Comment by NelsonYong** [comment]
但是在编码顶层规范利于维护，因为 use-fetchs的设计也是用户层面的最顶，尽管它内部采用的不是最顶方式

**Comment by NelsonYong** [comment]
我尝试在内部使用一下watch进行动态创建interval 去监听 pollingInterval

**Comment by NelsonYong** [comment]
@coderlcb  v1.3.6-alpha.1 尝试使用一下，我自测了一下没问题

**Comment by NelsonYong** [comment]
如果可以，后续会修复上一版

**Comment by NelsonYong** [comment]
```vue
<template>
  <div
  >读取用户名称：<span>{{ loading ? 'loading' : data }}</span>
    <br>
    <p>轮询间隔：{{ computedTime }}</p>
    <vhp-button @click="start()">开始轮询</vhp-button>
    <vhp-button @click="update()">轮询时间加100</vhp-button>
    <vhp-button @click="cancel()">停止</vhp-button>
  </div>
</template>

<script lang="ts" setup>
  import { computed, ref } from 'vue'
  import { useRequest } from 'vue-hooks-plus'

  function getUsername(): Promise<string> {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(String(Date.now()))
      }, 1000)
    })
  }

  const time = ref(2000)

  const computedTime = computed(() => time.value + 100)

  const { data, run, loading, cancel } = useRequest(() => getUsername(), {
    manual: true,
    pollingInterval: computedTime,
    pollingWhenHidden: false,
  })

  const start = () => {
    run()
  }

  const update = () => {
    time.value += 100
  }
</script>
```
这是我自测的demo，采用计算属性去改变 @coderlcb

**Comment by coderlcb** [comment]
> ```
> <template>
>   <div
>   >读取用户名称：<span>{{ loading ? 'loading' : data }}</span>
>     <br>
>     <p>轮询间隔：{{ computedTime }}</p>
>     <vhp-button @click="start()">开始轮询</vhp-button>
>     <vhp-button @click="update()">轮询时间加100</vhp-button>
>     <vhp-button @click="cancel()">停止</vhp-button>
>   </div>
> </template>
> 
> <script lang="ts" setup>
>   import { computed, ref } from 'vue'
>   import { useRequest } from 'vue-hooks-plus'
> 
>   function getUsername(): Promise<string> {
>     return new Promise((resolve, reject) => {
>       setTimeout(() => {
>         resolve(String(Date.now()))
>       }, 1000)
>     })
>   }
> 
>   const time = ref(2000)
> 
>   const computedTime = computed(() => time.value + 100)
> 
>   const { data, run, loading, cancel } = useRequest(() => getUsername(), {
>     manual: true,
>     pollingInterval: computedTime,
>     pollingWhenHidden: false,
>   })
> 
>   const start = () => {
>     run()
>   }
> 
>   const update = () => {
>     time.value += 100
>   }
> </script>
> ```
> 
> 这是我自测的demo，采用计算属性去改变 @coderlcb

可以实现了，我使用`const computedInterval = computed(() => generalStore.pollingInterval);`就可以了，用ref来保存不行，computed就可以。。。。
