### ISSUE TITLE
useRequest的相关类型没有导出

### ISSUE THREAD

**Issue by dmyz** [InhiblabCore/vue-hooks-plus#43]
类型没有导出

**Comment by NelsonYong** [comment]
我不太明白你的意思，可以具体一些吗？

全量的类型在types文件夹中导出，拆包类型在对应的es和lib文件夹中，可以查阅一下。

**Comment by NelsonYong** [comment]
我会第一时间跟进 @dmyz

**Comment by dmyz** [comment]
@NelsonYong useRequest 封装分页hook，自带分页hook不适用

**Comment by NelsonYong** [comment]
@dmyz  可以贴出代码来看看吗

**Comment by NelsonYong** [comment]
@dmyz  是我那个分页hook不适用你的场景吗

**Comment by dmyz** [comment]
![image](https://user-images.githubusercontent.com/15307200/203987604-765bdc1b-2ff5-47f0-99f7-c496c89357aa.png)

**Comment by dmyz** [comment]
@NelsonYong defaultParams  这个怎么赋值

**Comment by NelsonYong** [comment]
@dmyz  defaultParams的话你传进去就好了

**Comment by NelsonYong** [comment]
@dmyz  你可以采取解构的形式，将默认值置于最前

**Comment by NelsonYong** [comment]
是我没理解到吗 ？😂

**Comment by NelsonYong** [comment]
你应该在service函数中传入你想要的值
```typescript
()=>service({...pagination,current:pagination.current ?? defaultcurrnt})
```

**Comment by NelsonYong** [comment]
实际上一开始你就已经指定 current为 1，这就是默认值，你直接传进去就好了

**Comment by NelsonYong** [comment]
所以我有点不太明白defaultparams有什么问题 @dmyz

**Comment by dmyz** [comment]
@NelsonYong 好的，我再看看，ahooks 的useRequest怎么用的。
我之前用的这个 vue-request，传参不一样

**Comment by NelsonYong** [comment]
用法都应该差不多。你想表达的是不是既可以外部传其他值进来，又能使用table自己的参数，所以你想要默认参数。 @dmyz

**Comment by NelsonYong** [comment]
我提个建议，hook新增第二个参数params，由外部传进来，到时和service组合使用

**Comment by dmyz** [comment]
好的，我这还有个问题。
table分页，servie返回 `{ "": 0, list: [] }`
hook 返回 `list: []`
现在面临一个问题，servie返回结果和hook要的结果不一致a

**Comment by NelsonYong** [comment]
两种方案，比较推荐项目规范，code msg data三层需要和后端协商，第二种，可以写一个异步函数包一下这个service函数，await获取到值后，到时resolve出hook要的结构即可。 @dmyz

**Comment by NelsonYong** [comment]
一般来说，这和hook关系其实不大，hook不会指定要拿data这个字段，完全是用户返回什么就是什么，需要用户自己去，如axios设定拦截器返回对应的结构

**Comment by dmyz** [comment]
types
`
import { Ref, WatchSource } from 'vue';
import { CachedData } from 'vue-hooks-plus/es/useRequest/utils/cache';

export interface Options<TData, TParams extends unknown[]> {
  manual?: boolean;

  onBefore?: (params: TParams) => undefined;
  onSuccess?: (data: TData, params: TParams) => undefined;
  onError?: (e: Error, params: TParams) => undefined;
  onFinally?: (params: TParams, data?: TData, e?: Error) => undefined;

  defaultParams?: TParams;

  // 依赖更新
  refreshDeps?: WatchSource[] | unknown;
  refreshDepsAction?: () => undefined;

  // loading延迟
  loadingDelay?: number | Ref<number>;

  // 格式化数据
  formatResult?: (data?: TData) => unknown;

  // 轮询
  pollingInterval?: Ref<number> | number;
  pollingWhenHidden?: boolean;

  // 屏幕聚焦重新请求
  refreshOnWindowFocus?: Ref<boolean> | boolean;
  focusTimespan?: Ref<number> | number;

  // 防抖
  debounceWait?: number;
  debounceLeading?: Ref<boolean>;
  debounceTrailing?: Ref<boolean>;
  debounceMaxWait?: Ref<number>;

  // 节流
  throttleWait?: number;
  throttleLeading?: Ref<boolean>;
  throttleTrailing?: Ref<boolean>;

  // 请求缓存
  cacheKey?: String;
  cacheTime?: number;
  staleTime?: number;
  setCache?: (data: CachedData<TData, TParams>) => undefined;
  getCache?: (params: TParams) => CachedData<TData, TParams> | undefined;

  // 错误重试
  retryCount?: number;
  retryInterval?: number;

  // 只有当 ready 为 true 时，才会发起请求
  ready?: Ref<boolean> | boolean;

  // [x: string]: unknown
}

export interface Result<TData, TParams extends unknown[]> {
  loading: Ref<boolean>;
  data?: TData;
  error?: Error;
  params: TParams | [];
  cancel: () => void;
  refresh: () => void;
  refreshAsync: () => Promise<TData>;
  run: (...params: TParams) => void;
  runAsync: (...params: TParams) => Promise<TData>;
  mutate: (data?: TData | ((oldData?: TData) => TData | undefined)) => void;
}

export type Service = <R, Params extends any[]>(...params: Params) => Promise<R>;

export interface Data {
  total: number;
  list: any[];
}

export type Params = [{ current: number; pageSize: number; [key: string]: any }, ...any[]];

export type PaginationService<TData extends Data, TParams extends Params> = (...params: TParams) => Promise<TData>;

export interface PaginationResult<TData extends Data, TParams extends Params> extends Result<TData, TParams> {
  dataSource: any[] | undefined;
  pagination: {
    current: number;
    pageSize: number;
    defaultCurrent: number;
    defaultPageSize: number;
    total: number;
    // totalPage: number;
    onChange: (pageInfo: { current: number; pageSize: number }) => void;
  };
}

export interface PaginationOptions<TData extends Data, TParams extends Params> extends Options<TData, TParams> {
  defaultPageSize?: number;
  defaultCurrent?: number;
}
`
ts
`
import { Data, Params, PaginationResult, PaginationService, PaginationOptions } from './types';
import useRequest from 'vue-hooks-plus/es/useRequest';

const useHttpPagination = <TData extends Data, TParams extends Params>(
  service: PaginationService<TData, TParams>,
  options: PaginationOptions<TData, TParams> = {},
) => {
  const { defaultCurrent = 1, defaultPageSize = 20, ...rest } = options;

  const requestResult = useRequest<TData, TParams, any>(service, {
    defaultParams: [{ current: defaultCurrent, pageSize: defaultPageSize }],
    refreshDepsAction: () => {
      changeCurrent(1);
    },
    ...rest,
  });

  // const { current = 1, pageSize = defaultPageSize } = requestResult.params.value[0] || {};

  const total = requestResult.data?.value.total || 0;

  const onChange = ({ current, pageSize }: { current: number; pageSize: number }) => {
    let toCurrent = current <= 0 ? 1 : current;
    const toPageSize = pageSize <= 0 ? 1 : pageSize;
    const tempTotalPage = Math.ceil(total / toPageSize);
    if (toCurrent > tempTotalPage) {
      toCurrent = Math.max(1, tempTotalPage);
    }

    const [oldPaginationParams = {}, ...restParams] = requestResult.params.value || [];

    requestResult.run(
      {
        ...oldPaginationParams,
        current: toCurrent,
        pageSize: toPageSize,
      },
      ...restParams,
    );
  };

  /**
   * 分页
   * @param current 当前页
   */
  const changeCurrent = (current: number) => {
    onChange({ current, pageSize: 20 });
  };

  const { current = 1, pageSize = defaultPageSize } = requestResult.params.value[0] || {};

  const result: PaginationResult<TData, TParams> = {
    loading: requestResult.loading,
    data: requestResult.data?.value,
    dataSource: requestResult.data?.value.list,
    error: requestResult.error?.value,
    params: requestResult.params.value,
    cancel: requestResult.cancel,
    refresh: requestResult.refresh,
    refreshAsync: requestResult.refreshAsync,
    run: requestResult.run,
    runAsync: requestResult.runAsync,
    mutate: requestResult.mutate,
    pagination: {
      current,
      pageSize,
      defaultCurrent,
      defaultPageSize,
      total,
      onChange,
    },
  };
  return result;
};

export default useHttpPagination;
`

**Comment by NelsonYong** [comment]
我明天看看 @dmyz

**Comment by NelsonYong** [comment]
我不太明白为啥要吧use-request的类型自己再封装一遍呢

**Comment by dmyz** [comment]
类型怎么导出， 没export

**Comment by NelsonYong** [comment]
你就直接export导出就好了，然后从这个文件中拿😂

**Comment by NelsonYong** [comment]
如果可以的话可以给我一个在线例子或者仓库，并且描述具体一些，目前我还没办法完全明白你的意思

**Comment by dmyz** [comment]
我弄好了，换了一种思路好了

**Comment by NelsonYong** [comment]
好的，1.4.2修复了类型检查报错，可以更一下看看 @dmyz
