### ISSUE TITLE
在pinia中使用会报错

### ISSUE THREAD

**Issue by 1061875478** [InhiblabCore/vue-hooks-plus#52]
我将useRequest写在pinia的action中，从别的的地方调用action会警告
`[Vue warn]: onUnmounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.`
请问正确的姿势是什么

**Comment by NelsonYong** [comment]
信息告诉你需要在setup里面使用。正确姿势就是在setup里面使用use request，然后引入请求函数，看一下文档

**Comment by NelsonYong** [comment]
@1061875478 你的问题得到解决了嘛

**Comment by 1061875478** [comment]
感谢回复，看了相关文档解决了

**Comment by NelsonYong** [comment]
@1061875478  没问题就好，有问题第一时间解决哈，预计近段时间会推出国际化和美化文档，好用可以推荐给身边的小伙伴哈，感谢支持～

**Comment by 1061875478** [comment]
> @1061875478 没问题就好，有问题第一时间解决哈，预计近段时间会推出国际化和美化文档，好用可以推荐给身边的小伙伴哈，感谢支持～

挺好用的，可以多一些业务示例，这方面react的例子蛮多的
