### ISSUE TITLE
[useRequest]: 类型定义没有默认值

### ISSUE THREAD

**Issue by l246804** [InhiblabCore/vue-hooks-plus#57]
## 问题

开发时发现 `useRequest` 的类型定义没有赋默认值，导致每次调用都需传入三个类型。

![image](https://user-images.githubusercontent.com/53589602/207879467-34f33027-28c7-49e7-8e9a-0445700a34c1.png)

## 期望

可以仅传入单个类型定义。

**Comment by NelsonYong** [comment]
use-request实际上可以自动推导出data type和 params，一般在业务代码中比较少传入，都在API处进行管理即可。文档中有许多例子可以参考，返回promise<Type>那么Type就是data的类型，至于params你传入的时候会自动推导

单个类型定义这个问题会支持，这一块是有所欠缺的

**Comment by l246804** [comment]
其次还有 `data` 和 `error` 类型错误问题，应该是 `Ref<TData | undefined>`，但现在是 `Ref<TData> | undefined`，这样会导致误以为 `data` 和 `error` 默认是 `undefined`，但实际上是 `ref` 对象。

![image](https://user-images.githubusercontent.com/53589602/208004830-e996091b-bc13-43c7-a722-24891e673884.png)

**Comment by NelsonYong** [comment]
PR #58  #61
