### ISSUE TITLE
[useRequest]: 增加 `createUseRequest` 功能，提供全局创建 `useRequest` 实例。

### ISSUE THREAD

**Issue by l246804** [InhiblabCore/vue-hooks-plus#59]
## 原因

由于项目内需使用自定义插件和固定格式的数据处理，`useRequest` 仅支持单个接口调用传入，目前若想实现需自行导入 `vue-hooks-plus/es/useRequestImplement`，较为麻烦，期望能导出常用插件集合和该函数。

![image](https://user-images.githubusercontent.com/53589602/208005759-b047c330-f2d0-4863-8fee-63e24ea964cc.png)

## 期望

增加 `createUseRequest` 功能，提供全局创建 `useRequest` 实例。

**Comment by NelsonYong** [comment]
譬如这种全局的数据管理，我们更偏向于用户在使用axios或者request的时候，在拦截器中进行管理，use-request更专注于充当中间层的角色。use-request的插件功能解决的问题是现有功能无法拓展的前提下给予用户拓展的空间，它仍处于观察中，它或许并不是最优考虑的，全局的实例需要后续进行一个考量

**Comment by l246804** [comment]
也许我描述有误，并非全局创建实例，仅是支持能够独立创建一个 `useRequest`，毕竟库内导出的并不能满足我的需求，数据管理方面我仍然会使用 `axios` 的拦截器进行处理，但是我希望能够扩充一个插件进行 `useRequest` 和 `axios` 之间的沟通，若无法自行创建 `useRequest`，我需要在每次使用时传入自定义插件，这挺麻烦的。

**Comment by NelsonYong** [comment]
@l246804  你可以自定义一个hook，里面写`userequest`，把`userequest`的配置扔出去，加入插件，那这样就可以不用每次都传入自定义插件
```
function usexxx<TData, TParams,TPlugins>(service,options){
  const  data= useRequest(service, options,你的插件 plugins)
  return data
}

```

**Comment by l246804** [comment]
暂时就这样处理了。

**Comment by l246804** [comment]
没有导出插件的类型定义。

![image](https://user-images.githubusercontent.com/53589602/208015462-58981d15-57b4-4439-b247-d2bc54001ab2.png)

**Comment by NelsonYong** [comment]
`vue-hooks-plus/lib/useRequest/types` @l246804

**Comment by l246804** [comment]
也不行，没有导出。

**Comment by l246804** [comment]
能在 `vue-hooks-plus/types/index.d.ts` 中导出吗？

**Comment by NelsonYong** [comment]
后续会考虑一下导出结构进行增加，type主要作为playground的全量类型
