### ISSUE TITLE
[useRequest]: 增加初始值设置

### ISSUE THREAD

**Issue by l246804** [InhiblabCore/vue-hooks-plus#60]
## 原因

通常调用接口后会对返回数据进行空值检验，调用 `useRequest` 后若直接使用 `data` 变量在初始时无法改变其 `undefined` 状态，仅能通过 `computed(() => data.value || [])` 进行包装处理。

![image](https://user-images.githubusercontent.com/53589602/208006609-8bcde506-c96a-47c1-82e8-7d175479607f.png)

## 期望

希望能增加 `initialData` 来设置初始的数据状态，便于直接使用 `data` 变量进行业务处理。

**Comment by l246804** [comment]
上面的示例图体现不是很明显，但在常见的业务开发中，表格数据等，并不希望获取到的数据是 `undefined`，这很不友好，若需要用户自行处理就需要返回可读可写的 `computed`，无疑增加了代码维护成本，也破坏了代码的阅读性，如果存在 `initialData`，用户可自行决定是否传入，配合 `formatResult` 我觉得体验会更佳。

**Comment by NelsonYong** [comment]
你这个想法💡我觉得非常好，你可以尝试通过插件的形式去实现，目前应该暂不考虑拓展default value这个功能

**Comment by l246804** [comment]
好的 ok，主要在于增加插件实现功能也需要改写类型定义，如果能够官方内置当然是最好的:smile:。

**Comment by NelsonYong** [comment]
目前还不考虑这块，因为可能通用的场景都是 `data` 从 `undefined` 到有值，认识几个大兄弟都是基于我这个自己封装属于直接的钩子，像你这块，你可以封装一个自己业务通用的可能会比我这改进好一些，属于自己的高自定义😃

**Comment by l246804** [comment]
ok

**Comment by NelsonYong** [comment]
@l246804 最近也收到很多设置初始值的需求，已增加 `initialData ` 

PR #90

**Comment by NelsonYong** [comment]
https://inhiblabcore.github.io/docs/hooks/useRequest/basic/#result
