### ISSUE TITLE
[useRequest] 现在是否有支持请求前中断调用的方式

### ISSUE THREAD

**Issue by l246804** [InhiblabCore/vue-hooks-plus#63]
## 原因

开发业务时，表单的提交希望能在接口调用前进行校验，失败则终止本次调用，然而我发现 `onBefore` 内并没没有介绍可中断后续操作的 `api`。

![image](https://user-images.githubusercontent.com/53589602/209264378-003414fb-7ddd-490f-b884-a7d510ba3d2d.png)

## 期望

支持调用前的中断进行中断。

**Comment by NelsonYong** [comment]
可以声明一个校验函数，里面校验成功了就调用 submit 提交

**Comment by NelsonYong** [comment]
看你这个写法，建议使用 run

**Comment by NelsonYong** [comment]
`runAsync` 需要自己捕获错误

**Comment by l246804** [comment]
axios 已经做过错误兜底了，这里仅用来让按钮自动加载使用。

**Comment by l246804** [comment]
我看到插件可以通过 `stopNow` 中止调用，但是普通的 `onBefore` 没有，是否会加上呢？

**Comment by l246804** [comment]
不过若是需要校验，可能还需支持异步返回？

**Comment by NelsonYong** [comment]
按我的理解，你可以在表单提交的时候经过一个 `onFinish`的异步函数中，里面对字段进行校验，校验完成后再进行 `run` 即可，实际上你校验的操作由你外部的另外一个函数做

**Comment by NelsonYong** [comment]
> 我看到插件可以通过 `stopNow` 中止调用，但是普通的 `onBefore` 没有，是否会加上呢？

这个在 `option 的 onBefore`暂时不会考虑设置这个 `stopNow`，在我认为作为一个回调的生命周期函数最好是不影响这个函数本身，它只起到这个周期到达了再进行通知的一个目的。

至于插件可以，我想这个属于一个探索的过程吧，目前整个 `use-request` 也还是处于一个探索的阶段

**Comment by l246804** [comment]
暂时解决了，vant的表单可以直接通过组件实例调用，按钮绑定了组件实例的提交动作，刚好 vant 表单提供了校验成功后的事件通知，完美解决:smile:。
