### ISSUE TITLE
[useRequest] debounceMaxWait 类型定义错误

### ISSUE THREAD

**Issue by l246804** [InhiblabCore/vue-hooks-plus#71]
## 问题

配置项 `debounceMaxWait` 的类型定义为 `Ref<number>`，实际上支持 `number`。

![image](https://user-images.githubusercontent.com/53589602/209627621-5788b20e-3b5d-41ad-8a14-8f602a376ab0.png)

## 期望

类型定义正确。

### System Info

```shell
- `vue-hooks-plus@1.4.6`
- `vue@latest`
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't [already an issue](https://github.com/InhiblabCore/vue-hooks-plus/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueHooks Plus issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/InhiblabCore/vue-hooks-plus/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by inhiblab** [comment]
感谢反馈

**Comment by NelsonYong** [comment]
PR #73 
更新版本：[v1.4.7](https://github.com/InhiblabCore/vue-hooks-plus/releases/tag/v1.4.7)
