### ISSUE TITLE
useCounter文档例子书写错误

### ISSUE THREAD

**Issue by chenyjam** [InhiblabCore/vue-hooks-plus#8]
![image](https://user-images.githubusercontent.com/24648575/186085150-100e5a7a-9dbd-4020-a2eb-91621d48bf60.png)

**Comment by NelsonYong** [comment]
> 

已经修改，感谢纠正

**Comment by NelsonYong** [comment]
@chenyjam 已修改，感谢纠正

**Comment by NelsonYong** [comment]
已完成
