### ISSUE TITLE
祝大家新年快乐 🧨

### ISSUE THREAD

**Issue by NelsonYong** [InhiblabCore/vue-hooks-plus#81]
### Description

VueHooks Plus 团队提前预祝大家新年快乐 🧨

### Suggested solution

- 钱兔 🐰 无量

### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by undefined9999** [comment]
兔飞猛进

**Comment by NelsonYong** [comment]
> 兔飞猛进

新年快乐🎆
