### ISSUE TITLE
请问一下，为什么每个请求都会被触发2次？

### ISSUE THREAD

**Issue by jamessawyer** [InhiblabCore/vue-hooks-plus#9]
在使用 vue-hooks-plus 时，发现每个请求都会被触发2次，这是合理的吗？
```vue
function getUsername(): Promise<string> {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      console.log(666);

      resolve('yong_git');
    }, 1000);
  });
}

const { data } = useRequest(() => {
  console.log('🔥🔥'); // 打印2次
  return getUsername();
});
```

在线链接：[stackblitz](https://stackblitz.com/edit/vitejs-vite-xremmb?file=src/components/HelloWorld.vue)

**Comment by NelsonYong** [comment]
@jamessawyer 因为我在处理ready的时候使用的是watch effect进行依赖收集，ready默认为true，导致manual 自动一次，ready自动执行一次，现已改为watch忽略第一次执行，npm package已经更新至 v1.1.1版本

**Comment by jamessawyer** [comment]
懂了，感谢。已更新，测试可以👍
