### ISSUE TITLE
可以录视频或者写文档讲讲useRequest 的设计思路，看了一下源码，不懂为何这么设计。

### ISSUE THREAD

**Issue by jackchoumine** [InhiblabCore/vue-hooks-plus#96]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/InhiblabCore/vue-hooks-plus/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://inhiblabcore.github.io/docs/hooks).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by NelsonYong** [comment]
感谢你的支持 🌸

设计 `useRequest` 的思路和益处 👇
[Juejin post](https://juejin.cn/post/7143488626955911181)

详细思路和源码解析在有时间的时候我会写一版博客，可以关注一下我的掘金账号！
